---
.travis.yml:
  secure: "FB+GouH3vel0+lcCFpctGorICXLEEyMa1C7qlJ9IZVBlW59rV/8ZOZg6rYdTGJ5VzSKN2oG/QPnjT//LucGMptjMPJafnXEkBhwP3QBzDdg+LSYjTBov0h8bpIjyycGvGXV5ERVSzSonkJuCdO92/pnP5nMFXGI0NVpvE7v2X1Y="
.rubocop.yml:
  include_todos: true
